= 3. Variables
:sectanchors:
:source-highlighter: pygments

== 3.1 Add a top level variable
Open your `Main.kt` file, and before your main function, declare a top-level mutable variable `currentWeather` as follows:


[source,kotlin]
----
// Top-level mutable variable, accessible throughout the project
var currentWeather: String = "Sunny"

fun main(args: Array<String>) {

}
----

This variable will represent the current weather conditions and can be accessed throughout your project

== 3.2 Add member variables
Next, we'll create classes with member variables. For this, first, make a new package named `participants` within the main package `com.example.f1app`. Then, inside the `participants` package, create a `Driver` class:

[source,kotlin]
----
import java.util.*

class Driver(
    val name: String,
    var points: Int = 0,
    val uuid: UUID = UUID.randomUUID(),
)
----

The `Driver` class includes three member variables: `name`, `points`, and `uuid`. `name` and `uuid` are immutable (read-only), while `points` is mutable.

Now, let's create another class, `RaceCar`, with additional member variables:

[source,kotlin]
----
import kotlin.random.Random

class RaceCar (
    val carNumber: Int,
    val maxSpeed: Double = Random.nextDouble(200.0, 230.0),
    private var currentSpeed: Double = 0.0,
    internal var currentLap: Int = 0,
    internal var isPitStopNeeded: Boolean = false,
) {
}
----

The `RaceCar` class includes several member variables with different visibility levels: `carNumber` and `maxSpeed` are publicly accessible and immutable, while `currentSpeed`, `currentLap`, and `isPitStopNeeded` are mutable with differing levels of visibility.


== 3.3 Add local variables

We're going to introduce local variables into our `RaceCar` class. The code changes include:

1. `numLaps`: This is a constructor parameter that will determine the number of laps for a particular instance of our class.

2. `lapTimes`: This is a member variable that will be initialized using the `numLaps` constructor parameter. It's meant to store the lap times for our instance.

3. `addLapTime`: This is a member function that will add a lap time to our `lapTimes` member variable. The function will take parameters that are local to it.

Here's a step-by-step breakdown:

=== 3.3.1 Add `numLaps` constructor parameter
We will add `numLaps` as a constructor parameter. This parameter will represent the number of laps for each instance of the class.

[source,kotlin,highlight=7]
----
import kotlin.random.Random

class RaceCar (
    val carNumber: Int,
    val maxSpeed: Double = Random.nextDouble(200.0, 230.0),
    private var currentSpeed: Double = 0.0,
    internal var currentLap: Int = 0,
    internal var isPitStopNeeded: Boolean = false,
    numLaps: Int,
) {
}
----

=== 3.3.2 Create `lapTimes` member variable
Next, we will create a member variable named `lapTimes`. We will use the `numLaps` constructor parameter to initialize this variable. The purpose of `lapTimes` is to store the time it took to complete each lap. Additionally, we will set its setter to be `private` to restrict direct modification from outside the class.

[source,kotlin,highlight=9,10]
----
import kotlin.random.Random

class RaceCar (
    val carNumber: Int,
    val maxSpeed: Double = Random.nextDouble(200.0, 230.0),
    private var currentSpeed: Double = 0.0,
    internal var currentLap: Int = 0,
    internal var isPitStopNeeded: Boolean = false,
     numLaps: Int,
) {
    var lapTimes = arrayOfNulls<Double>(numLaps)
        private set
}
----

In this code, the `private set` modifier restricts the ability to modify `lapTimes` directly from outside of the RaceCar class. This ensures that lap times can only be updated through designated methods within the class (such as a method to add a lap time), thereby providing better control over the data.


=== 3.3.3 Create `addLapTime` member function
Finally, we will create a member function named `addLapTime`. This function will take parameters that are local to it. The function's purpose is to add a lap time to the lapTimes member variable.

[source,kotlin,highlight=11..13]
----
import kotlin.random.Random

class RaceCar (
    val carNumber: Int,
    val maxSpeed: Double = Random.nextDouble(200.0, 230.0),
    private var currentSpeed: Double = 0.0,
    internal var currentLap: Int = 0,
    internal var isPitStopNeeded: Boolean = false,
     numLaps: Int,
) {
    var lapTimes = arrayOfNulls<Double>(numLaps)

    fun addLapTime(lapNumber: Int, time: Double) {
        lapTimes[lapNumber] = time
    }
}
----

== 3.4 Try them in Scratch file
Use the Scratch file (usually named `scratch.kts`) in your IDE to instantiate the `RaceCar` and `Driver` classes, and to interact with their properties. The Scratch file can be found under *Scratches and Consoles* > *Scratches*.

First, create instances of `RaceCar` and `Driver` classes and print some of their properties. Remember to import the necessary classes:

[source,kotlin]
----
import com.example.f1app.participants.Driver
import com.example.f1app.participants.RaceCar

val car1 = RaceCar(
    carNumber = 1,
    numLaps = 5
)
println("Car 1 max speed: ${car1.maxSpeed}")

val driver1 = Driver(name = "Max Verstappen")
println("Driver 1 name: ${driver1.name}")

----

Afterward, modify some mutable properties and observe how they alter the state of the objects:

[source,kotlin]
----
println("driver points: ${driver1.points}")
driver1.points = 100
println("driver points: ${driver1.points}")

println("Car 1 lap 0 time: ${car1.lapTimes[0]}")
car1.addLapTime(lapNumber = 0, time = 123.45)
println("Car 1 lap 0 time: ${car1.lapTimes[0]}")

----

Now, try manipulating the top-level variable currentWeather:

[source,kotlin]
----
import com.example.f1app.currentWeather

// ...
println("Current weather: $currentWeather")
currentWeather = "Snow"
println("Current weather: $currentWeather")
----

Finally, attempt to access ``RaceCar``'s `internal`, `private` variables, and try to modify the `lapTimes` array directly. Can you figure out what's happening and why?

➡️ link:./4-constants.adoc[Variables]
⬅️ link:./2-prepare-kotlin-project.adoc[2. Prepare an F1 Simulator Kotlin Project]
